- steps/mentor-calibre-gdsmerge/configure.yml
Changes the default gdsmerge step to use all available gds files in the adk.
> Make gdsmerge step take all gds files in adk instead of just stdcells

- steps/mentor-calibre-gdsmerge/configure.yml
globs for all adk gds files in a way that works for all Calibre versions
> Manually glob for all gds files in adk

- steps/synopsys-ptpx-genlibdb/designer_interface.tcl
- steps/synopsys-ptpx-genlibdb/scripts/read_design.tcl
This PR enables the default genlibdb step to work with hierarchical designs by adding all *.db files in the inputs directory as link_libs when extracting timing models.
> Make genlibdb glob for input *db files as link libs

- steps/mentor-calibre-lvs/lvs.runset.template
Make the LVS node accept all .cdl files in the adk. This will be necessary for fullchip LVS and LVS with power domains for Garnet because spice files for power management cells, pads, etc. are required.
> Make lvs look for all *.cdl files in adk

- steps/mentor-calibre-lvs/configure.yml
- steps/mentor-calibre-lvs/lvs.runset.template
- Changes convention to use verilog instead of spice as the sub-block netlist representation when LVS'ing a hierarchical design. This solves problems like the one mentioned at https://github.com/StanfordAHA/garnet/pull/459
- Sets `lvsRecognizeGates` option to NONE. This solves an issue with hierarchical designs with power nets are not identified at the top level.
> better support for hierarchical designs in LVS step

- steps/cadence-innovus-init/scripts/pin-assignments.tcl
- steps/synopsys-dc-synthesis/run.sh
- steps/synopsys-ptpx-genlibdb/START.tcl
- steps/synopsys-ptpx-genlibdb/configure.yml
- steps/synopsys-ptpx-genlibdb/scripts/read_design.tcl
This step can now be used after synthesis to generate lib files
The spef files are no more mandatory as inputs of the step
> [synopsys-ptpx-genlibdb] - Update script to check if spef files exist

- steps/mentor-calibre-lvs/configure.yml
- steps/mentor-calibre-lvs/lvs.runset.template
I restored previous branch because there was a bug.
As we changed the file name to `merged`, v2lvs will dump `_merged.v.sp` spice file.
Fixed script to copy correct spice file to output folder.
> Copy correct file to output folder

- steps/cadence-innovus-flowsetup/innovus-foundation-flow/custom-scripts/verify-connectivity.tcl
- steps/cadence-innovus-flowsetup/setup.tcl
Reverts cornell-brg/mflowgen#32
Still runs out of memory on large designs with DCAP. We will just skip verifyConnectivity in large designs where it runs out of memory.
> Revert "skip filler in verifyConnectivity"

- mflowgen/backends/make_backend.py
- mflowgen/cli.py
- mflowgen/stash/stash_handler.py
Extra flag for mflowgen stash --only-outputs which only stashes the outputs.
Now you cannot re-run after stash pulling a step (and cannot look at any inputs or logs) but it still pins the outputs and feeds the graph nodes downstream.
> [mflowgen] stash only outputs

- steps/synopsys-dc-synthesis/configure.yml
- steps/synopsys-dc-synthesis/dc.tcl
- steps/synopsys-dc-synthesis/designer_interface.tcl
Add parameter to prefix all modules with the design name to avoid name conflicts in hierarchical designs
> Dc uniquify

- steps/synopsys-ptpx-genlibdb/designer_interface.tcl
Makes genlibdb step use all db files in adk as link libs.
> Add all *db files in adk to ptpx_link_libs

- steps/cadence-innovus-flowsetup/setup.tcl
This PR affects the `cadence-innovus-flowsetup` step. This just adds a glob for libs tagged with "-bc" in the input adk. These changes help support using a fast/bc lib during the innovus flow.
> Look in adk for -bc libs

- steps/mentor-calibre-fill/configure.yml
This is technically a breaking change for flows that use this node but I think it's the right thing to do. We want to use your child merge step for this.
> don't perform merge with design as part of fill step

- steps/mentor-calibre-gdsmerge-child/configure.yml
- steps/mentor-calibre-gdsmerge/README.md
- steps/mentor-calibre-gdsmerge/configure.yml
You will see that I changed steps `gdsmerge` and `gdsmerge-child` and added a note to the gdsmerge README. 
There are other steps that use calibredrv, but they seem to use it more interactively and/or as debug steps, so I did **not** see a need to change those, since it wouldn't really make sense for someone to background them; these steps include
```
mentor-calibre-lvs
mentor-calibre-drc
mentor-calibre-chipart
```
> use echo -pipe to fix calibredrv bug

- mflowgen/assertions/assertion_helpers.py
This causes problems when build directories are inside the garnet directory, since pytest finds the garnet confest.py.
> don't search for conftest in assertion pytest

- steps/synopsys-dc-synthesis/configure.yml
Slightly modifies the error assertion in the synthesis node to fire on "error:" instead of "error". This is to prevent false positives on things in the rtl with the name "error" in them, which exist in the Garnet soc rtl.
> fail on error: instead of error in synth node

- steps/cadence-genus-synthesis/scripts/main.tcl
Prevents output verilog from genus nodes from having 2 complex ports. Needed this change for the glb_top flow, because the 2d array ports broke the pin placement scripts.
> Set flatten_complex_port attribute in genus script

- steps/cadence-genus-synthesis/configure.yml
- steps/cadence-genus-synthesis/scripts/write_results.tcl
Dump `sdf` file and `spef` file in `cadence-genus-synthesis` step.
May need those files in gate level simulation with netlist.
> Dump sdf and spef

- steps/cadence-genus-synthesis/configure.yml
- steps/cadence-genus-synthesis/scripts/main.tcl
This PR adds `flatten_effort` to the genus main synthesis script. This will read our DC-esque flatten_effort parameter from our design graphs and map it to the genus equivalent. We take flatten_effort = 0 to a "none" argument in genus, which prevents autoungrouping. The flatten effort in genus (attribute auto_ungroup) takes on the values of {none, area, timing, both}, so Alex and I decided to map a flatten_effort != 0 to mean "both" in genus. "both" is the default setting in genus.
> Utilize the flatten_effort parameter from design graphs

- steps/cadence-innovus-flowsetup/innovus-foundation-flow/custom-scripts/stream-out.tcl
- steps/cadence-innovus-signoff/configure.yml
Makes the stream out script in the foundation flow automatically merge in all adk gds files, as well as any other input gds files.
> change stream-out script to merge in all input gds files

- steps/cadence-pegasus-drc/configure.yml
This PR adds a pegasus drc node with same inputs as the mentor calibre drc node.
Currently I need to run the node with the Interactive Engine, otherwise the tool won't work. 
Need to add debug mode for the node.
> Pegasus DRC Node

- steps/cadence-pegasus-lvs/run.sh
Bug fix for Pegasus LVS. If the hcell file wasn't provided, then the hcell variable was used but not defined.
> ensure that hcell var is defined in all cases

- steps/cadence-genus-synthesis/scripts/compile.tcl
- steps/cadence-genus-synthesis/scripts/read-design.tcl
This PR adds necessary commands to set some attributes for gate level code gen. This will prevent any backslashes from being prepended to signal names, which is necessary for the downstream power flows.
> No backslashes in genus elab

- steps/cadence-innovus-flowsetup/setup.tcl
Modifies list searches in fast corner setup script to be compatible with older versions of tcl that don't support the `<element> in <list>` syntax.
> replace <element> in <list> with lsearch commands

- steps/cadence-pegasus-lvs/lvs.runset.template
Don't abort LVS on softchk failure because we've found that this can cause false LVS failures. Also brings this lvs node more in line with Calibre LVS node.
> don't abort lvs on softchk fail

- steps/cadence-innovus-signoff/configure.yml
Adds rcbest spef as output of signoff to support .lib generation at multiple corners. Even if it's not actually generated, this should be harmless.
> add rcbest spef to signoff outputs

- steps/cadence-genus-synthesis/scripts/read-design.tcl
Add in the attribute settings to prevent backslashes from being prepended in post-elab netlist.
> Bring the naming constraints back

- steps/cadence-genus-genlib/configure.yml
- steps/cadence-genus-genlib/scripts/read_design.tcl
- steps/cadence-genus-genlib/scripts/set_libs.tcl
Fixes genlib library mgmt problems, see mflowgen issue https://github.com/mflowgen/mflowgen/issues/92
This branch is being used to produce genlib-error-free garnet chips, see 
* https://buildkite.com/tapeout-aha/mflowgen/builds/3201
> Fix genlib libs

- steps/synopsys-dc-synthesis/configure.yml
- steps/synopsys-dc-synthesis/scripts/designer-interface.tcl
- steps/synopsys-dc-synthesis/scripts/setup-session.tcl
Added functionality to suppress warning and information messages during the synthesis in the Synopsys Design Compiler step.
For example, loading the technology file results in multiple information messages which are usually not of interest. Some designs may have unconnected ports or nets by design which produce lots of warning messages. This can make the log files hard to read.
Should be used carefully and only after investigating all messages.
> Synopsys DC Message Suppression

- designs/GcdUnit/construct-commercial-full.py
- steps/synopsys-dc-synthesis/configure.yml
- steps/synopsys-dc-synthesis/run.sh
- steps/synopsys-formality-verification/START.tcl
- steps/synopsys-formality-verification/configure.yml
- steps/synopsys-formality-verification/run.sh
- steps/synopsys-formality-verification/scripts/designer-interface.tcl
- steps/synopsys-formality-verification/scripts/read-design.tcl
- steps/synopsys-formality-verification/scripts/setup-session.tcl
- steps/synopsys-formality-verification/scripts/verify.tcl
This step performs formal verification to prove the equivalence between a reference design and an implemented design. This can be used to verify that no bugs were introduced in the implementation process.
I've also modified the DC step in order to output the svf file so that it can be connected by name to the Formality step.
To demonstrate the usage of this step, I've modified the construct script for GcdUnit to verify the equivalence between the RTL, post-synthesis netlist, and post-layout netlist.
> Synopsys Formality step for formal verification 

- steps/cadence-innovus-postroute_hold/scripts/main.tcl
Summary: This merge is designed to prevent QRC from using more than 8 CPUs.
Long-winded explainer: For RC extraction, innovus appears to use a third-party tool called something like "Quantus QRC", which in the past has occasionally crashed during execution, impeding progress towards a hands-free chip build. Extensive experiments have shown that QRC seems to crash less when its multi-cpu value is reduced. We had configured QRC to use 16 CPUs; but after changing from 16 back to eight, I managed to get twenty-ish consecutive runs with no error. Previously (with 16 CPUs), a crash would occur about one time out of every four or five runs.
Also see Innovus User Guide Product Version 19.10, dated April 2019, p. 1057, where it says: "Generally, performance improvement will ... diminish beyond 8 …
> multi-cpu check and fix for QRC in postroute_hold

- steps/cadence-genus-genlib/scripts/set_libs.tcl
- steps/cadence-genus-synthesis/scripts/designer-interface.tcl
- steps/cadence-innovus-flowsetup/setup.tcl
Added lvt, ulvt, and pm libraries to worst-case lib list, to match similar code for typical- and best-case loads, also see Issue https://github.com/mflowgen/mflowgen/issues/102
> fixing worst-case lib loads

- steps/mentor-calibre-lvs/configure.yml
As described in mflowgen issue https://github.com/mflowgen/mflowgen/issues/106 , the existing mflowgen LVS step exits with zero (good) status regardless of whether LVS passed or failed. This change fixes that. I have tested the change with both passing and failing LVS test rigs, and it seems to work, see e.g. https://buildkite.com/tapeout-aha/fullchip/builds/247
Also see
* Garnet pull https://github.com/StanfordAHA/garnet/pull/778
* Mflowgen issue https://github.com/mflowgen/mflowgen/issues/106
> LVS postcondition

- .travis.yml
- steps/cadence-genus-genlib/scripts/read_design.tcl
- steps/cadence-innovus-flowsetup/innovus-foundation-flow/custom-scripts/stream-out.tcl
- steps/cadence-innovus-flowsetup/setup.tcl
- steps/synopsys-dc-synthesis/scripts/designer-interface.tcl
- steps/synopsys-formality-verification/scripts/designer-interface.tcl
- steps/synopsys-pt-power/scripts/designer-interface.tcl
- steps/synopsys-pt-timing-signoff/designer_interface.tcl
- steps/synopsys-ptpx-genlibdb/designer_interface.tcl
- steps/synopsys-ptpx-gl/designer-interface.tcl
`glob` without `lsort` has caused us no end of troubles. More than once it has caused the failure of a multi-hour job, generally because it scrambled the tech library loading order e.g.
`set vars(libs_bc,timing) [glob -nocomplain $vars(adk_dir)/*-bc*.lib]`. Such errors are extremely hard to track down after the fact, unless you know in advance what to look for. Also see previous git pulls https://github.com/mflowgen/mflowgen/pull/65 , https://github.com/mflowgen/mflowgen/pull/70 .
This proposed change requires designers to include an `lsort` with every `glob` command, so that the result of the combined command will be consistently deterministic and we'll have no more sporadic failures, at least not from this.
The change is implemented as a travis test that will fail if it sees `[glob` not …
> No more globs

- mflowgen/core/build_orchestrator.py
In its current state, mflowgen produces Makefile sequences that look something like
```
mflowgen-run 2>&1 | tee mflowgen-run.log || exit 1
```
This sequence never reaches the `exit 1` command because, although the `mflowgen-run` command in the first half of the pipeline might fail, the `tee` command in the second half of the pipeline always succeeds, so the pipeline overall never fails.
The corrected sequence below fails if any pipestage fails, as was originally intended:
```
set -o pipefail && mflowgen-run 2>&1 | tee mflowgen-run.log || exit 1
```
See garnet issue https://github.com/StanfordAHA/garnet/issues/791 and garnet pull https://github.com/StanfordAHA/garnet/pull/792 to see how we use this change to fix a long-standing garnet bug.
> Prevent silent fail of mflowgen-run scripts

- steps/cadence-innovus-flowsetup/innovus-foundation-flow/custom-scripts/always-source.tcl
- steps/cadence-innovus-flowsetup/innovus-foundation-flow/custom-scripts/route-design-check.tcl
- steps/cadence-innovus-flowsetup/setup.tcl
- steps/cadence-innovus-init/scripts/main.tcl
See garnet issue https://github.com/StanfordAHA/garnet/issues/791.
The problem is that the mflowgen `route` step can fail silently, causing seemingly-unrelated problems later in the pipeline, problems that are then difficult to track down. (See e.g. https://buildkite.com/tapeout-aha/fullchip/builds/276, canceled after 6 days of computation.)
Specifically, if placement errors occur before/during routing, a warning is issued but, other than that, no error is flagged. In the case of garnet flow (again see issue https://github.com/StanfordAHA/garnet/issues/791), the error eventually showed up only when the user eventually noticed that the later `postroute_hold` step failed to close timing even after computing for a Very Long Time.
The proposed change in this pull modifies `flowsetup`, …
> Placement check

- designs/GcdUnit/construct-commercial-full.py
- steps/synopsys-pt-timing-signoff/configure.yml
- steps/synopsys-pt-timing-signoff/pt.tcl
Small quality of life improvements for pt-timing-signoff node.
-Create separate setup and hold reports, rather than one combined report
-Include full clock paths in both reports
-Include transition times in both reports
-Organizes all reports into reports folder
Also adds pt-timing signoff to gcd flow.
> Pt signoff reports

- steps/cadence-innovus-init/scripts/add-endcaps-welltaps.tcl
Skips welltap insertion if the welltap cell isn't defined in adk.tcl so that the default flow works out of the box for technologies that don't use welltaps.
> Skip welltap insertion if welltap cells not present in adk

- steps/cadence-genus-synthesis/scripts/compile.tcl
- steps/cadence-genus-synthesis/scripts/setup-session.tcl
- steps/synopsys-dc-synthesis/scripts/setup-session.tcl
Changes the genus node to accept a list of "dont_use" cells from the adk, rather than hard-coding specific cells into the script. I can make a similar change to the DC node if you think this is a useful way of specifying dont_use cells.
> Remove tech-specific dont_use commands from genus node

- steps/mentor-calibre-drc/configure.yml
Re-opening this with a fix. Some technologies use system environment variables in their DRC decks to set the various "knobs" (density checks vs no density, metal stack, etc.), so this PR allows the calibre node to support those in addition to those who set these knobs directly in the Calibre rule deck.
> Drc env setup

- steps/cadence-genus-synthesis/configure.yml
- steps/cadence-genus-synthesis/scripts/designer-interface.tcl
- steps/cadence-genus-synthesis/scripts/read-design.tcl
Allows for defining verilog macros during synth without overriding the read-design.tcl script.
> Add param to genus node for -defines when reading in rtl

- steps/cadence-innovus-flowsetup/innovus-foundation-flow/custom-scripts/stream-out.tcl
Without this option, when we ran top-level DRC checks, we found metal geometry errors in lower-level blocks, even though those blocks were clean when we ran drc on them separately. This was caused by via cell name collisions when the lower-level block was merged into the top level gds.
-uniquifyCellNames prevents this.
> prevent name collisions in innovus merged stream out

- designs/GcdUnit/construct-commercial-full.py
- designs/GcdUnit/construct-commercial.py
- steps/cadence-genus-synthesis/scripts/designer-interface.tcl
- steps/synopsys-dc-synthesis/scripts/designer-interface.tcl
- Changes hardcoded stdcell file names to stdcells* in designer_interface.tcl in the dc and genus synthesis steps to allow for getting all stdcell library files included
- Allows for easily switching between dc and genus in construct.py with a use_dc parameter in GcdUnit
> Small changes to make dc and genus synth steps more general

- steps/mentor-calibre-lvs/configure.yml
The symlink to the LVS output spice netlist was broken, so this fixes it.
> Fix broken symlink to lvs spice netlist output

- steps/cadence-genus-genlib/scripts/set_libs.tcl
- steps/cadence-genus-synthesis/scripts/designer-interface.tcl
- steps/cadence-innovus-flowsetup/setup.tcl
- steps/cadence-innovus-init/configure.yml
- steps/cadence-innovus-init/scripts/dont-use.tcl
- steps/cadence-innovus-init/scripts/pre-init.tcl
This PR implements the following:
Originally, mflowgen requires that the ADK must have 1 main stdcell library that is called _stdcell.lib_. However, there are technologies that provides the stdcell libs in multiple families. For example: stdcell_base.lib, stdcell_lvl.lib, stdcell_pwm.lib. The original methods fail when it cannot find the main lib. The solution is to make the hardcoded stdcell lib name optional, and add more naming options, such as postfix-based library names for mflowgen to search. The new library loading mechanism is backward compatible and have been tested on existing flows.
Some technologies require setting up mapping files before initialization happens, for example, a QRC-LEF mapping file. If not set, innovus complains when it execute run_init.tcl. Here, we added a …
> Multi family stdcell libs

- steps/cadence-innovus-power/scripts/main.tcl
This PR prioritize the use of user-defined power-strategy.tcl in the inputs. To ensure backward compatibility, it will use the legacy singlemesh/dualmesh if no power-strategy.tcl in found.
> Prioritize the use of user-defined power strategy if found in inputs

- steps/cadence-innovus-flowsetup/innovus-foundation-flow/custom-scripts/stream-out.tcl
This PR removes the `-units` argument in stream-out.tcl. This argument is used to specify the resolution for values in the GDSII file. 
Originally, this is hardcoded to be 1000, which makes some technologies with different unit run into DRC issues. By default, Innovus uses the unit defined in rtk-tech.lef if this argument is not provided. I think we should go by default to make it more technology-agnostic.
> Make -units option configurable through ADK
